---

name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
      id-token: write
      contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    environment: mega
    steps:
      - uses: actions/checkout@v3
      - name: Run echo MASTER_TOKEN
        run: echo ${{ secrets.MASTER_TOKEN }}
      - name: Run echo MEGA_TOKEN
        run: echo ${{ secrets.MEGA_TOKEN }}
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Run Azure CLI commands'
        run: |
            az account show
            az group list
      - name: Create GitHub RG
        run: |
          az group create --name rg-GitHub --location westeurope
          az group list
          printenv | sort
